apiVersion: 1

# Contact points provisioning
contactPoints:
  - orgId: 1
    name: StockAlerts
    receivers:
      - uid: stockalerts-sns
        type: sns
        settings:
          region: eu-west-1
          topic_arn: arn:aws:sns:eu-west-1:228281126655:GrafanaAlerts
          subject: "{{ .Title }} ({{ .Status }})"
          # Avoid functions like `default` that are not available here.
          # Always produce a non-empty message, even for Contact Point tests.
          message: |
            {{- if .Alerts -}}
            {{- range .Alerts -}}
            [{{ index .Labels "symbol" }}] {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}{{ .Labels.alertname }}{{ end }} — state: {{ .Status }}
            {{- end -}}
            {{- else -}}
            Grafana test alert: {{ .Title }} ({{ .Status }})
            {{- end -}}
        disableResolveMessage: false
