name: Python package tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-market-tracker:
    name: Market Tracker tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov schemathesis fastapi sqlalchemy pandas yfinance httpx
          pip install -r market-tracker/requirements.txt
          pip install -e ./market-tracker

      - name: Run unit tests
        env:
          COVERAGE_FILE: .coverage.market_tracker.unit
          DATABASE_URL: sqlite:///./market_tracker_unit.db
        run: |
          pytest market-tracker/tests/unit -m unit \
            --cov=market-tracker/app \
            --cov-report=xml:coverage-market-tracker-unit.xml \
            --cov-report=term \
            --cov-fail-under=85

      - name: Run integration tests
        env:
          COVERAGE_FILE: .coverage.market_tracker.integration
          DATABASE_URL: sqlite:///./market_tracker_integration.db
        run: |
          pytest market-tracker/tests/integration -m integration \
            --cov=market-tracker/app \
            --cov-report=xml:coverage-market-tracker-integration.xml \
            --cov-report=term \
            --cov-fail-under=85

      - name: Run contract tests
        env:
          COVERAGE_FILE: .coverage.market_tracker.contract
          DATABASE_URL: sqlite:///./market_tracker_contract.db
        run: |
          pytest market-tracker/tests/contract -m contract \
            --cov=market-tracker/app \
            --cov-report=xml:coverage-market-tracker-contract.xml \
            --cov-report=term \
            --cov-fail-under=85

  test-yahoo-etl:
    name: Yahoo ETL tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov schemathesis fastapi sqlalchemy pandas yfinance httpx schedule
          pip install -r yahoo_etl/requirements.txt
          pip install -e ./yahoo_etl

      - name: Run unit tests
        env:
          COVERAGE_FILE: .coverage.yahoo_etl.unit
          DATABASE_URL: sqlite:///./yahoo_etl_unit.db
        run: |
          pytest yahoo_etl/tests/unit -m unit \
            --cov=yahoo_etl \
            --cov-report=xml:coverage-yahoo-etl-unit.xml \
            --cov-report=term \
            --cov-fail-under=85

      - name: Run integration tests
        env:
          COVERAGE_FILE: .coverage.yahoo_etl.integration
          DATABASE_URL: sqlite:///./yahoo_etl_integration.db
        run: |
          pytest yahoo_etl/tests/integration -m integration \
            --cov=yahoo_etl \
            --cov-report=xml:coverage-yahoo-etl-integration.xml \
            --cov-report=term \
            --cov-fail-under=85
