name: Yahoo ETL CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    name: Yahoo ETL tests (pytest)
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov schemathesis fastapi sqlalchemy pandas yfinance httpx schedule
          pip install -r yahoo_etl/requirements.txt
          pip install -e ./yahoo_etl

      - name: Run unit tests
        env:
          COVERAGE_FILE: .coverage.yahoo_etl.unit
          DATABASE_URL: sqlite:///./yahoo_etl_unit.db
        run: |
          set -e
          if [ -d yahoo_etl/tests/unit ]; then
            TARGET="yahoo_etl/tests/unit"
            MARKER="-m unit"
          else
            TARGET="yahoo_etl/tests"
            MARKER=""
          fi
          pytest ${TARGET} ${MARKER} \
            --cov=yahoo_etl \
            --cov-report=xml:coverage-yahoo-etl-unit.xml \
            --cov-report=term

      - name: Run integration tests
        env:
          COVERAGE_FILE: .coverage.yahoo_etl.integration
          DATABASE_URL: sqlite:///./yahoo_etl_integration.db
        run: |
          set -e
          if [ -d yahoo_etl/tests/integration ]; then
            pytest yahoo_etl/tests/integration -m integration \
              --cov=yahoo_etl \
              --cov-report=xml:coverage-yahoo-etl-integration.xml \
              --cov-report=term
          else
            echo "No integration tests found for Yahoo ETL. Skipping."
          fi
